INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 1, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 1, 0, 1, 1, 238);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 1, 0, 1, 2, 131);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 1, 0, 1, 3, 195);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 1, 0, 2, 1, 271);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 1, 0, 2, 2, 467);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 1, 0, 2, 3, 157);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 2, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 2, 0, 1, 1, 175);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 2, 0, 1, 2, 1735);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 2, 0, 1, 3, 1100);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 2, 0, 2, 1, 40);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 2, 0, 2, 2, 811);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 2, 0, 2, 3, 809);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 3, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 3, 0, 1, 1, 1733);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 3, 0, 1, 2, 1405);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 3, 0, 1, 3, 126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 3, 0, 2, 1, 246);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 3, 0, 2, 2, 234);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 3, 0, 2, 3, 121);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 4, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 4, 0, 1, 1, 173);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 4, 0, 1, 2, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 4, 0, 1, 3, 1307);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 4, 0, 2, 1, 1126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 4, 0, 2, 2, 190);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 4, 0, 2, 3, 348);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 5, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 5, 0, 1, 1, 1058);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 5, 0, 1, 2, 1276);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 5, 0, 1, 3, 181);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 5, 0, 2, 1, 1289);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 5, 0, 2, 2, 1474);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 5, 0, 2, 3, 228);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 6, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 6, 0, 1, 1, 151);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 6, 0, 1, 2, 1103);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 6, 0, 1, 3, 1685);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 6, 0, 2, 1, 1519);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 6, 0, 2, 2, 350);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 6, 0, 2, 3, 166);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 7, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 7, 0, 1, 1, 237);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 7, 0, 1, 2, 663);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 7, 0, 1, 3, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 7, 0, 2, 1, 176);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 7, 0, 2, 2, 467);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 7, 0, 2, 3, 1735);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 8, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 8, 0, 1, 1, 234);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 8, 0, 1, 2, 195);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 8, 0, 1, 3, 1100);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 8, 0, 2, 1, 126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 8, 0, 2, 2, 157);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 8, 0, 2, 3, 809);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 9, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 9, 0, 1, 1, 190);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 9, 0, 1, 2, 1405);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 9, 0, 1, 3, 271);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 9, 0, 2, 1, 175);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 9, 0, 2, 2, 1307);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 9, 0, 2, 3, 1733);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 10, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 10, 0, 1, 1, 228);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 10, 0, 1, 2, 1126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 10, 0, 1, 3, 238);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 10, 0, 2, 1, 811);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 10, 0, 2, 2, 246);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 10, 0, 2, 3, 1289);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 11, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 11, 0, 1, 1, 1685);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 11, 0, 1, 2, 1276);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 11, 0, 1, 3, 173);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 11, 0, 2, 1, 131);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 11, 0, 2, 2, 40);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 11, 0, 2, 3, 121);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 12, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 12, 0, 1, 1, 1103);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 12, 0, 1, 2, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 12, 0, 1, 3, 181);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 12, 0, 2, 1, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 12, 0, 2, 2, 1519);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 12, 0, 2, 3, 237);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 13, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 13, 0, 1, 1, 350);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 13, 0, 1, 2, 1058);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 13, 0, 1, 3, 663);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 13, 0, 2, 1, 348);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 13, 0, 2, 2, 151);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 13, 0, 2, 3, 1474);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 14, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 14, 0, 1, 1, 166);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 14, 0, 1, 2, 176);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 14, 0, 1, 3, 157);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 14, 0, 2, 1, 1405);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 14, 0, 2, 2, 809);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 14, 0, 2, 3, 190);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 15, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 15, 0, 1, 1, 1289);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 15, 0, 1, 2, 234);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 15, 0, 1, 3, 1735);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 15, 0, 2, 1, 271);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 15, 0, 2, 2, 1126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 15, 0, 2, 3, 467);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 16, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 16, 0, 1, 1, 1685);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 16, 0, 1, 2, 228);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 16, 0, 1, 3, 1100);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 16, 0, 2, 1, 1307);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 16, 0, 2, 2, 121);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 16, 0, 2, 3, 238);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 17, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 17, 0, 1, 1, 1519);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 17, 0, 1, 2, 1276);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 17, 0, 1, 3, 126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 17, 0, 2, 1, 175);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 17, 0, 2, 2, 237);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 17, 0, 2, 3, 173);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 18, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 18, 0, 1, 1, 350);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 18, 0, 1, 2, 181);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 18, 0, 1, 3, 811);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 18, 0, 2, 1, 131);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 18, 0, 2, 2, 1733);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 18, 0, 2, 3, 663);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 19, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 19, 0, 1, 1, 1058);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 19, 0, 1, 2, 1103);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 19, 0, 1, 3, 176);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 19, 0, 2, 1, 195);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 19, 0, 2, 2, 246);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 19, 0, 2, 3, 40);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 20, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 20, 0, 1, 1, 348);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 20, 0, 1, 2, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 20, 0, 1, 3, 166);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 20, 0, 2, 1, 1474);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 20, 0, 2, 2, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 20, 0, 2, 3, 151);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 21, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 1, 1, 1405);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 1, 2, 1289);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 1, 3, 1100);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 2, 1, 467);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 2, 2, 1685);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 2, 3, 157);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 22, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 1, 1, 1519);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 1, 2, 190);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 1, 3, 228);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 2, 1, 234);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 2, 2, 1735);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 2, 3, 173);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 23, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 1, 1, 350);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 1, 2, 237);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 1, 3, 238);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 2, 1, 809);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 2, 2, 1733);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 2, 3, 1276);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 24, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 1, 1, 1058);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 1, 2, 811);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 1, 3, 1307);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 2, 1, 126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 2, 2, 1103);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 2, 3, 131);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 25, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 1, 1, 348);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 1, 2, 176);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 1, 3, 181);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 2, 1, 271);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 2, 2, 121);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 2, 3, 175);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 26, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 1, 151);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 2, 246);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 3, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 1, 663);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 2, 40);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 3, 1126);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 27, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 1, 1474);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 2, 195);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 3, 173);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 1, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 2, 166);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 3, 1733);
