INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 26, 0, '2006-06-24 08:45:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 1, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 2, 562);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 3, 1474);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 1, 181);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 2, 663);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 3, 1124);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 27, 0, '2006-06-24 08:51:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 1, 1027);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 2, 350);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 3, 246);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 1, 230);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 2, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 3, 811);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 28, 0, '2006-06-24 08:57:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 28, 0, 1, 1, 88);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 28, 0, 1, 2, 176);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 28, 0, 1, 3, 131);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 28, 0, 2, 1, 348);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 28, 0, 2, 2, 40);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 28, 0, 2, 3, 177);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 29, 0, '2006-06-24 09:03:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 29, 0, 1, 1, 166);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 29, 0, 1, 2, 1126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 29, 0, 1, 3, 1405);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 29, 0, 2, 1, 1733);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 29, 0, 2, 2, 839);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 29, 0, 2, 3, 237);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 30, 0, '2006-06-24 09:09:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 30, 0, 1, 1, 1725);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 30, 0, 1, 2, 1100);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 30, 0, 1, 3, 1519);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 30, 0, 2, 1, 151);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 30, 0, 2, 2, 1289);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 30, 0, 2, 3, 809);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 31, 0, '2006-06-24 09:15:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 31, 0, 1, 1, 1058);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 31, 0, 1, 2, 121);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 31, 0, 1, 3, 1735);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 31, 0, 2, 1, 126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 31, 0, 2, 2, 234);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 31, 0, 2, 3, 467);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 32, 0, '2006-06-24 09:21:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 32, 0, 1, 1, 1685);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 32, 0, 1, 2, 1103);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 32, 0, 1, 3, 238);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 32, 0, 2, 1, 562);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 32, 0, 2, 2, 271);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 32, 0, 2, 3, 1276);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 33, 0, '2006-06-24 09:27:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 33, 0, 1, 1, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 33, 0, 1, 2, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 33, 0, 1, 3, 1027);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 33, 0, 2, 1, 1307);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 33, 0, 2, 2, 228);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 33, 0, 2, 3, 88);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 34, 0, '2006-06-24 09:33:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 34, 0, 1, 1, 839);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 34, 0, 1, 2, 177);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 34, 0, 1, 3, 663);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 34, 0, 2, 1, 1474);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 34, 0, 2, 2, 157);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 34, 0, 2, 3, 195);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 35, 0, '2006-06-24 09:39:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 35, 0, 1, 1, 1124);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 35, 0, 1, 2, 246);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 35, 0, 1, 3, 230);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 35, 0, 2, 1, 40);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 35, 0, 2, 2, 173);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 35, 0, 2, 3, 190);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 36, 0, '2006-06-24 09:45:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 36, 0, 1, 1, 350);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 36, 0, 1, 2, 151);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 36, 0, 1, 3, 126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 36, 0, 2, 1, 237);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 36, 0, 2, 2, 1126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 36, 0, 2, 3, 1725);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 37, 0, '2006-06-24 09:51:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 37, 0, 1, 1, 809);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 37, 0, 1, 2, 195);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 37, 0, 1, 3, 166);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 37, 0, 2, 1, 1276);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 37, 0, 2, 2, 811);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 37, 0, 2, 3, 121);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 38, 0, '2006-06-24 09:57:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 38, 0, 1, 1, 562);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 38, 0, 1, 2, 175);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 38, 0, 1, 3, 467);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 38, 0, 2, 1, 181);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 38, 0, 2, 2, 176);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 38, 0, 2, 3, 1519);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 39, 0, '2006-06-24 10:03:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 39, 0, 1, 1, 1027);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 39, 0, 1, 2, 1733);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 39, 0, 1, 3, 88);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 39, 0, 2, 1, 177);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 39, 0, 2, 2, 131);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 39, 0, 2, 3, 1405);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 40, 0, '2006-06-24 10:09:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 40, 0, 1, 1, 348);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 40, 0, 1, 2, 839);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 40, 0, 1, 3, 1103);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 40, 0, 2, 1, 1100);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 40, 0, 2, 2, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 40, 0, 2, 3, 1058);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 41, 0, '2006-06-24 10:15:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 41, 0, 1, 1, 40);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 41, 0, 1, 2, 234);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 41, 0, 1, 3, 1685);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 41, 0, 2, 1, 1474);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 41, 0, 2, 2, 230);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 41, 0, 2, 3, 228);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 42, 0, '2006-06-24 10:21:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 42, 0, 1, 1, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 42, 0, 1, 2, 1725);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 42, 0, 1, 3, 663);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 42, 0, 2, 1, 1307);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 42, 0, 2, 2, 1124);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 42, 0, 2, 3, 271);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 43, 0, '2006-06-24 10:27:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 43, 0, 1, 1, 173);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 43, 0, 1, 2, 1289);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 43, 0, 1, 3, 166);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 43, 0, 2, 1, 151);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 43, 0, 2, 2, 1276);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 43, 0, 2, 3, 246);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 44, 0, '2006-06-24 10:33:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 44, 0, 1, 1, 238);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 44, 0, 1, 2, 175);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 44, 0, 1, 3, 176);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 44, 0, 2, 1, 88);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 44, 0, 2, 2, 1735);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 44, 0, 2, 3, 121);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 45, 0, '2006-06-24 10:39:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 45, 0, 1, 1, 177);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 45, 0, 1, 2, 181);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 45, 0, 1, 3, 1126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 45, 0, 2, 1, 157);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 45, 0, 2, 2, 190);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 45, 0, 2, 3, 562);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 46, 0, '2006-06-24 10:45:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 46, 0, 1, 1, 131);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 46, 0, 1, 2, 839);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 46, 0, 1, 3, 809);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 46, 0, 2, 1, 1027);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 46, 0, 2, 2, 467);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 46, 0, 2, 3, 195);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 47, 0, '2006-06-24 10:51:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 47, 0, 1, 1, 1405);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 47, 0, 1, 2, 811);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 47, 0, 1, 3, 1103);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 47, 0, 2, 1, 1124);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 47, 0, 2, 2, 1725);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 47, 0, 2, 3, 126);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 48, 0, '2006-06-24 10:57:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 48, 0, 1, 1, 230);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 48, 0, 1, 2, 237);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 48, 0, 1, 3, 234);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 48, 0, 2, 1, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 48, 0, 2, 2, 1519);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 48, 0, 2, 3, 1307);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 49, 0, '2006-06-24 11:03:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 49, 0, 1, 1, 271);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 49, 0, 1, 2, 348);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 49, 0, 1, 3, 1100);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 49, 0, 2, 1, 121);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 49, 0, 2, 2, 663);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 49, 0, 2, 3, 173);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 50, 0, '2006-06-24 11:09:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 50, 0, 1, 1, 1058);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 50, 0, 1, 2, 151);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 50, 0, 1, 3, 157);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 50, 0, 2, 1, 1733);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 50, 0, 2, 2, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 50, 0, 2, 3, 228);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 51, 0, '2006-06-24 11:15:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 51, 0, 1, 1, 190);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 51, 0, 1, 2, 88);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 51, 0, 1, 3, 175);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 51, 0, 2, 1, 1474);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 51, 0, 2, 2, 350);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 51, 0, 2, 3, 1126);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 52, 0, '2006-06-24 11:21:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 52, 0, 1, 1, 1027);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 52, 0, 1, 2, 166);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 52, 0, 1, 3, 40);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 52, 0, 2, 1, 1276);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 52, 0, 2, 2, 562);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 52, 0, 2, 3, 467);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 53, 0, '2006-06-24 11:27:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 53, 0, 1, 1, 177);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 53, 0, 1, 2, 246);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 53, 0, 1, 3, 1289);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 53, 0, 2, 1, 1124);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 53, 0, 2, 2, 1685);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 53, 0, 2, 3, 1735);
INSERT INTO game_match (match_level, match_number, match_index, time_scheduled, status_id) VALUES (0, 54, 0, '2006-06-24 11:33:00', 1);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 54, 0, 1, 1, 157);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 54, 0, 1, 2, 839);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 54, 0, 1, 3, 195);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 54, 0, 2, 1, 238);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 54, 0, 2, 2, 230);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 54, 0, 2, 3, 1725);
