INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 21, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 1, 1, 1405);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 1, 2, 1289);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 1, 3, 1100);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 2, 1, 467);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 2, 2, 1685);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 21, 0, 2, 3, 157);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 22, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 1, 1, 1519);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 1, 2, 190);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 1, 3, 228);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 2, 1, 234);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 2, 2, 1735);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 22, 0, 2, 3, 173);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 23, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 1, 1, 350);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 1, 2, 237);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 1, 3, 238);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 2, 1, 809);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 2, 2, 1733);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 23, 0, 2, 3, 1276);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 24, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 1, 1, 1058);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 1, 2, 811);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 1, 3, 1307);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 2, 1, 126);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 2, 2, 1103);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 24, 0, 2, 3, 131);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 25, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 1, 1, 348);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 1, 2, 176);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 1, 3, 181);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 2, 1, 271);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 2, 2, 121);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 25, 0, 2, 3, 175);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 26, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 1, 151);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 2, 246);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 1, 3, 571);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 1, 663);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 2, 40);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 26, 0, 2, 3, 1126);
INSERT INTO game_match (match_level, match_number, match_index, status_id) VALUES (0, 27, 0, 0);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 1, 1474);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 2, 195);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 1, 3, 173);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 1, 125);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 2, 166);
INSERT INTO alliance_team (match_level, match_number, match_index, alliance_color_id, position, team_number) VALUES (0, 27, 0, 2, 3, 1733);
